app:
  crypto:
    card-secret-key: ${CARD_SECRET_KEY:change-this-card-secret-key-32-char}
  kafka:
    topics:
      card-created: card-created-events
    outbox:
      publisher:
        fixed-delay-ms: 5000

  jwt:
    secret: ${JWT_SECRET:change-this-jwt-secret-key-minimum-64-chars}
    access:
      expiration: ${JWT_ACCESS_EXPIRATION:3600000}
    refresh:
      expiration: ${JWT_REFRESH_EXPIRATION:604800000}

  cors:
    allowed-origins:
      - ${FRONTEND_URL:http://localhost:5173}

server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_cards_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 30000
        request.timeout.ms: 10000
        max.in.flight.requests.per.connection: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  liquibase:
    change-log: classpath:db/migration/db.migration-master.yaml

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.example.bankcards: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:DEBUG}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:TRACE}