server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: transaction-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transaction_card}
    username: ${SPRING_DATASOURCE_USERNAME:${TRANSACTION_DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${TRANSACTION_DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

app:
  kafka:
    topics:
      card-created: card-created-events
      balance-changed: balance-changed-events